In [10]:
class TreeNode(object):
    def __init__(self,x):
        self.val = x
        self.left = None
        self.right = None
def kth_smallest(root,k):
    stack=[]
    while root or stack:
        while root:
            stack.append(root)
            root=root.left
        root = stack.pop()
        k-=1
        if k==0:
            break
            root = root.right
    return root.val
root = TreeNode(8)
root.left = TreeNode(5)
root.right = TreeNode(14)
root.left.left = TreeNode(4)
root.left.right =TreeNode(6)
root.left.right.left = TreeNode(8)
root.left.right.right = TreeNode(7)
root.right.right = TreeNode(24)
root.right.right.left = TreeNode(22)
print(kth_smallest(root,2))
print(kth_smallest(root,3))

4
4


In [ ]:
# kth smallest element in a givren BST

In [ ]:
#an array is a subset of an otehr aray

In [13]:
def isSubset(arr1,arr2,m,n):
    i=0
    j=0
    for i in range(n):
        for j in range(m):
            if(arr2[i] == arr1[j]):
                break
        if(j==m):
            return 0
    return 1

In [14]:
if __name__ == "__main__":
    arr1 = [11,1,3,4,7,2]
    arr2 = [12]
    m= len(arr1)
    n= len(arr2)
    if(isSubset(arr1,arr2,m,n)):
        print("arr2 is subset of arr1")
    else:
        print("is not")

arr2 is subset of arr1


In [22]:
def find_sumPair(arr,n,k):
    i = 0
    j = n-1
    while(i<j):
        if(arr[i]+arr[j]==k):
            return 1
        elif (arr[i]+arr[j]<k):
            i=i+1
        else:
            j = j-1
    return -1
    

In [31]:
if __name__ == "__main__":
    arr = [1,2,5,4,7]
    k = 9
    if(find_sumPair(arr,n,k)):
        print("")
    else:
        print("no")

yes


In [ ]:
#A+B=K

In [32]:
def countX(lst,x):
    count = 0
    for ele in lst:
        if (ele == x):
            count = count + 1
    return count


In [33]:
lst = [8,6,8,10,8,2,8,6,10]
x = 8
print('{} has occurred {} times'.format(x,countX(lst,x)))

8 has occurred 4 times


In [ ]:
#element occurrences

In [6]:
NO_OF_CHARS = 256
def canFormPalindrome(st):
    count = [0]*(NO_OF_CHARS)
    for i in range(0,len(st)):
        count[ord(st[i])] = count[ord(st[i])] + 1
    odd = 0
    
    for i in range(0,NO_OF_CHARS):
        if (count[i] & 1):
            odd = odd +1
        if (odd>1):
            return False
    return True
    

In [7]:
if(canFormPalindrome("geeksforgeeks")):
    print("yes")
else:
    print("no")
    
if(canFormPalindrome("geeksogeeks")):
    print("yes")
else:
    print("no")

no
yes


In [ ]:
#palindrome

In [9]:
def oneDigit(num):
    return((num >= 0) and (num < 10));
def isPaliUtil(num,dupNum):
    if(oneDigit(num)):
        return(num== (dupNum) % 10);
    if(isPalUtil(int(num/10), dupNum) == False):
        return -1;
    dupNum = int(dupNum/10);
    return(num % 10 == (dupNum) % 10);


In [20]:
def isPossible(str,n):
    l = len(str)
    if (l>=n):
        return True
    return False


In [23]:
str = "anilina"
n = 9
if(isPossible(str,n)):
    print("yes")
else:
    print("no")

no


In [ ]:
#after removing n number of elements given string is still a palindrome

In [ ]:
#strirng into a special palindrome

In [37]:
s = "ABCdcba"
u =[0]*26
n = len(s)
for i in range(n):
    if(s[i].isupper()):
        u[ord(s[i])-65] += 1
    else:
        u[ord(s[i])-97] -= 1
fl = True
po = 0
ne = 0
for i in range(26):
    if(u[i]>0):
        po += u[i]
    if(u[i]<0):
        ne += u[i]
        
if(po ==0 and ne ==0):
    print("yes")
elif(po == 1 and ne == 0):
    print("yes")
elif(po == 0 and ne ==-1):
    print("yess")
else:
    print("no")

yess


In [ ]:
#count of substring whose chars can be rearranged to form the given word

In [38]:
def countOcc(s):
    cnt = 0
    for i in range(0, len(s) - 3):
        c,l,a,p = 0,0,0,0
        
        for j in range(i,i+4):
            if s[j] == 'c':
                c+=1
            elif s[j] == 'l':
                l += 1
            elif s[j] == 'a':
                a += 1
            elif s[j] == 'p':
                p += 1
        if c == 1 and l == 1 and a == 1 and p == 1:
            cnt += 1
    return cnt

In [39]:
if __name__ =="__main__":
    s="clapc"
    print(countOcc(s.lower()))

2


In [12]:
def find_sumPair(arr,n,k):
    i = 0
    j = n-1
    while(i<j):
        if(arr[i]+arr[j]==k):
            return 1
        elif(arr[i]+arr[j]):
            i = i+1
        else:
            j = j-1
    return -1

In [14]:
if __name__=="__main__":
    arr = [1,2,6]
    arr.sort()
    k = 0
    n = 0
    if(find_sumPair(arr,n,k)):
        print("yes")
    else:
        print("no")

NameError: name 'sort' is not defined

In [46]:
def printPairs(arr,arr_size,max):
    s = set()
    for i in range(0,arr_size):
        temp = max-arr[i]
        if(temp in s):
          print (" Pair with given max "  + str(max)  + " is ("+str(arr[i])+", "+str(temp)+")")
        s.add(arr[i])


In [47]:
A = [1,4,45,6,10,8]
n = 16
printPairs(A,len(A),n)

 Pair with given max 16 is (10, 6)


In [2]:
def isPalindrome(str):
    for i in xrange(0, len(str)/2):
        if str[i] != str[len(str)-i-1]:
            return False
    return True

In [8]:
str = "abcde"
ans = isPalindrome(str)

if (ans):
    print("yes")
else:
    print("no")

NameError: name 'xrange' is not defined

In [25]:
x = "malayalam"
w = ""
for i in x:
    w = i+w
    if (x==w):
        print("yes")
    else:
        print("no")

no
no
no
no
no
no
no
no
yes


In [13]:
def isPalindrome(s):
    rev = ''.join(reversed(s))
    if (s==rev):
        return True
    return False

In [16]:
s = "maayalam"
ans =  isPalindrome(s)
if (ans):
    print("yes")
else:
    print("no")

no


In [21]:
list = ['apple', 'banana', 'apple', 'tomato', 'carrot', 'apple', 'banana']
def checkIfDuplicates(list):
    for elem in list:
        if list.count(elem)>1:
            return True
    reutrn False

SyntaxError: invalid syntax (<ipython-input-21-18a29f77742c>, line 6)

In [48]:
def PrintRepeating(arr, n):
    for i in range(0, n):
        index = arr[i] % n
        arr[index] += n
    
    for i in range(0, n):
        if (arr[i]/n) > 1:
            print(i, end ="")

In [49]:
def PrintRepeating(arr, size):
    print("the repeating elements are: ")
    
    for i in range(0, size):
        if arr[abs(arr[i])]>=0:
            arr[abs(arr[i])] =- arr[abs(arr[i])]
        else:
            print(abs(arr[i]), end = "")
    

In [36]:
for i in range(10):
    print(i)
    if i > 5:
        pass
print("hello")

0
1
2
3
4
5
6
7
8
9
hello


In [39]:
list = []
for i in range(10):
    for j in range(10,20):
        list.append(i*j)
print(list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171]


In [40]:
list = [i*j for i in range(10) for j in range (10,20)]
print(list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171]


In [15]:
def factorial(n):
    if n>1:
        return n*factorial(n-1)
    else:
        return n

In [16]:
n = 5
print(factorial(n))

120


In [25]:
def fact(n):
    count = 1
    for i in range(1,n):
        count=n*fact(n-1)
    return count

In [26]:
n = 5
print(fact(n))

120


In [29]:
n = 5
fact = 1
for i in range(1,n+1): 
    fact = fact * i 
      
print ("The factorial of 05 is : ",end ="") 
print(fact) 

The factorial of 05 is : 120


In [61]:
def proper(some_text):
    some_text = some_text.strip()
    some_text = " ".join([some_text[0:5].upper() + some_text[5:]
for some_text in some_text.split()])
    return some_text


In [63]:
captian = proper("anil siddabathula siddhartha")
print(captian)

ANIL SIDDAbathula SIDDHartha


In [65]:
product = lambda x,y : x*y
print(product(4,4))

16


In [66]:
from datetime import datetime
def printDates(dates):
    for i in range(len(dates)):
        print(dates[i])
        
    

In [69]:
if __name__=="__main__":
    dates =["23 jan 2015", "25 nov 2015", "15 feb 2018", "02 may 2020"]
    dates.sort(key = lambda date : datetime.strptime(date, '%d %b %y'))
    printDates(dates)

ValueError: unconverted data remains: 15

In [17]:
from datetime import datetime
p = input("Enter the paragrpah:")
p = p.split(".")
p.pop()
print(p)
print(sorted(p, key = lambda year : datetime.strptime(year[3:7], '%Y')))
print('.'.join(sorted(p, key = lambda year : datetime.strptime(year[3:7], '%Y')))+'.')

Enter the paragrpah:iam 10 years old. iam 45 years old.iam 52 years old
['iam 10 years old', ' iam 45 years old']


ValueError: time data ' 10 ' does not match format '%Y'

In [1]:
class Word(object):
    def __init__(self, string, index):
        self.string = index
        self.index = index
    

In [8]:
def createDupArray(string, size):
    dupArray = []
    for i in range(size):
        dupArray.append(Word(string[i], i))
    return dupArray
    

In [10]:
def printAnagramsTogether(wordArr, size):
    dupArray = createDupArray(wordArr, size)
    for i in range(size):
        dupArray[i].string = ''.join(sorted(dupArray[i].string))
    dupArray = sorted(dupArray, key = lambda k: k.string)
    for word in dupArray:
        print (wordArr[word.index])
        

In [14]:
wordArr = ['cat','dog','tac','god','act']
size = len(wordArr)
printAnagramsTogether(wordArr, size)

TypeError: 'int' object is not iterable

In [1]:
from collections import defaultdict

In [8]:
def printAnagramsTogether(words):
    groupedWords = defaultdict(list)
    for word in words:
        groupedWords["".join(sorted(word))].append(word)
    
    for group in groupedWords.values():
        print("".join(group))


In [9]:
if __name__=="__main__":
    arr = ["cat", "dog", "tac", "god", "act"]
    printAnagramsTogether(arr)

TypeError: first argument must be callable or None

In [10]:
from collections import Counter

In [11]:
def checkAnagram(num1, num2):
    bin1 = bin(num1)[2:]
    bin2 = bin(num2)[2:]
    zeros = abs(len(bin1)-len(bin2))
    if(len(bin1)>len(bin2)):
        bin2 = zeros * '0' + bin2
    else:
        bin1 = zeros * '0' + bin1
        
    dict1 = Counter(bin1)
    dict2 = Counter(bin2)
        
    if dict1 == dict2:
        print("yes")
    else:
        print("no")

In [13]:
if __name__=="__main__":
    num1 = 8
    num2 = 4
    checkAnagram(num1,num2)

yes


In [15]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name':['anil', 'sunil', 'ramessh', 'sanu'], 'number': [25,22,20,21], 'group': ['mba', 'msc', 'ma','ms']})
print(df)

      name  number group
0     anil      25   mba
1    sunil      22   msc
2  ramessh      20    ma
3     sanu      21    ms


In [ ]:
import numpy as np
i port pandas as pd

In [18]:
#marekt_df.describe()     gives all numeric rows n columns , max , min , percentailes, std , mean , count
#market_df.info()        gives all the dtypes and other data related info
#market_df.head()
#market_df.tail()
#market_df.coulmns
#market_df.shape
#market_df.values
#market_df.set_index("col_name" , inplace = True)
#market_df.sort_index(axis = 0, ascending = False) 
#market_df.sort_values(by = 'shipping_cost' , inplace = True)
#market_df.sort_values(by=['prod_id','sales', ascending = False])
#market_df[['cust_id','sales','profit']].head()
#help(pd.DataFrame.iloc)
#market_df.iloc[2,4]
#help(pd.DataFrame.i)
#market_df.iloc[5]
#market_df.iloc[5, :]
#market_df.iloc[[3,7,8]]
#market_df.iloc[4:8]
#market_df.iloc[:, 3:8]
#market_df.ilo;c[2;5 , 3:8]
#marekt_df.loc[2,'sales']   
#iloc is integer location that is either integer based indexing or boolean based indexing we can give true or false 
#in the iloc we can give only indexes  #we can give label here instead of giving indexing
#market_df.loc['Ord_5406', ['sales','profit','cust_id']] it will pick ord_5406 colukmn and sales profit cust id rows
#df.sales>3000
#df.loc[df.sales>3000]
#df.loc[(df.sales>2000) | ]

#customer in baangalore = ["cust5406", "cust5454", "cust8452"]
#df.loc[df['cust_id'].isin(customer in baangalore)]

#grouping in pandas

df_by_segment['profit'].sum()
df_by_segment.profit.sum().sort_values(ascending = False)
df_by_segment['profit'].mean()

#together grouping and saying whether it is profit or not
by_product_cat_subcat = master_df.groupby(['prod_cat','prod_seg'])
by_product_cat_subcat['profit'].mean()

#describe the data aftere grouping  the columns in pandas datad frame
by_product_cat_subcat['profit'].describe()

In [1]:
5+7
type(5+7)

int

In [2]:
type(7.1-3.1)

float

In [3]:
type(13/5)

float

In [4]:
type("anil")

str

In [6]:
type('anil')

str

In [8]:
type(1j*4j)

complex

In [9]:
"hello" + "word"

'helloword'

In [11]:
"anil"+"ani"

'anilani'

In [14]:
"hello" *10 *0

''

In [7]:
u = [40,5,15,42,2,9]
for i in range(0,len(u)):
    for j in range(i+1,len(u)):
        t = 0
        m = 0
        if(i>j):
         t = u[j] + u[i]
         m = max(t,m) 

In [8]:
print("max", m)

max 0


In [9]:
import sys

In [10]:
def sum(a,n):
    maxVal = a[0]; maxCount = 1
    secondMax = sys.maxsize
    for i in range(1,n):
        if(a[i] == maxVal):
            maxCount += 1
        elif(a[i] > maxVal):
            secondMax = maxVal
            secondMaxCount = maxCount
            maxVal = a[i]
            maxCount = 1
        elif(a[i] == secondMax):
            secondMax = a[i]
            secondMaxCount += 1
        elif(a[i] > secondMax):
            secondMax = a[i]
            secondMaxcount = 1
    if(maxCount > 1):
        return maxCount * (maxCount - 1)/2
    return secondMaxCount

In [32]:
array = [4,4,2,5,2,4,5,2,4,52,4,52,4]
n = len(array)
print(sum(array, n))

1.0


In [24]:
def _sum(a,n):
    maxSum = -9999999
    for i in range(n):
        for j in range(n):
            maxSum = max(maxSum, a[i] + a[j])
    c = 0
    for i in range(n):
        for j in range(1+i, n):
            if a[i] + a[j] == maxSum:
                c += 1
    return c

In [31]:
array = [4,4,2,5,2,4,5,2,4,52,4,52,4]
n = len(array)
print(_sum(array, n))

1


In [40]:
def findLargestSumPair(arr,n):
    if arr[0] > arr[1]:
        first = arr[0]
        second = arr[1]
    else:
        first = arr[1]
        second = arr[0]
    for i in range(2,n):
        if arr[i]> first:
            second = first
            first = arr[i]
        elif arr[i]>second and arr[i] != first:
            second = arr[i]
    return (first + second)

In [41]:
arr = [12,45,74,41,15]
n = len(arr)
print("maxSumPair is", findLargestSumPair(arr,n))

maxSumPair is 119


In [15]:
import numpy

In [16]:
x = numpy.array([[1,2],[4,5]])
y = numpy.array([[7,8],[9,10]])

In [17]:
print('the element wise addition of matrix is :')
print(numpy.add(x,y))

the element wise addition of matrix is :
[[ 8 10]
 [13 15]]


In [18]:
print('the element wisse subtraction of matrix is :')
print(numpy.subtract(x,y))

the element wisse subtraction of matrix is :
[[-6 -6]
 [-5 -5]]


In [19]:
print('the element wisee subtraction of matrix is :')
print(numpy.divide(x,y))

the element wisee subtraction of matrix is :
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [20]:
print(numpy.dot(x,y))

[[25 28]
 [73 82]]


In [21]:
print(numpy.multiply(x,y))

[[ 7 16]
 [36 50]]


In [ ]:
#time series manipultaion

In [22]:
import pandas as pd
from datetime import datetime
import numpy as np

In [24]:
range_date = pd.date_range(start = '1/1/2019', end ='1/18/2019', freq = 'Min')
print(type(range_date[110]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [35]:
df = pd.DataFrame(range_date, columns = ['date'])
df['data'] = np.random.randint(0,100, size = (len(range_date)))
print(df.head(10))

                 date  data
0 2019-01-01 00:00:00    76
1 2019-01-01 00:01:00    54
2 2019-01-01 00:02:00     2
3 2019-01-01 00:03:00    57
4 2019-01-01 00:04:00    33
5 2019-01-01 00:05:00    27
6 2019-01-01 00:06:00    94
7 2019-01-01 00:07:00    58
8 2019-01-01 00:08:00    10
9 2019-01-01 00:09:00    14


In [37]:
string_data = [str(x) for x in range_date]
print(string_data[1:11])

['2019-01-01 00:01:00', '2019-01-01 00:02:00', '2019-01-01 00:03:00', '2019-01-01 00:04:00', '2019-01-01 00:05:00', '2019-01-01 00:06:00', '2019-01-01 00:07:00', '2019-01-01 00:08:00', '2019-01-01 00:09:00', '2019-01-01 00:10:00']


In [ ]:
#voewl palindrome

In [38]:
def vowel(c):
    v = list("aeiou")
    if c in v:
        return True
    return False


In [40]:
def palindrome(s):
    v = []
    for i in s:
        if vowel(i).append(i):
            if len(v) == 0:
                print("-1")
            else:
                x = v[::-1]
                f = 1
                for i in range(len(x)):
                    if x[i]! = v[i]:
                        f = 0
                        break
                if f==1:
                    print("yes")
                else:
                    print("no")

SyntaxError: invalid syntax (<ipython-input-40-3135bdc34f82>, line 11)

In [1]:
import statistics from maths


SyntaxError: invalid syntax (<ipython-input-1-877a74abd4c1>, line 1)